name: Build Docker Image and push to docker repo

on:
  push:
    paths-ignore:
      - ".github/workflows/**"
      - "poly_ubs_final.sql"
      - "poly_ubs_table.sql"
      - "poly_ubs_data.sql"

  pull_request:
    branches: ["dev"]
    paths-ignore:
      - ".github/workflows/**"
      - "poly_ubs_final.sql"
      - "poly_ubs_table.sql"
      - "poly_ubs_data.sql"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zetanox/ubrain:$(date +%s)
      
