# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: ["dev"]
    paths-ignore:
      - ".github/workflows/**"
      - "poly_ubs_final.sql"
      - "poly_ubs_table.sql"
      - "poly_ubs_data.sql"

  pull_request:
    branches: ["dev"]
    paths-ignore:
      - ".github/workflows/**"
      - "poly_ubs_final.sql"
      - "poly_ubs_table.sql"
      - "poly_ubs_data.sql"

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
      MONGODB_URL: ${{ secrets.MONGODB_URL }}

      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}

      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GHN_TOKEN: ${{ secrets.GHN_TOKEN }}

      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

      SHOP_ID: ${{ secrets.SHOP_ID }}

      SEPAY_ACCOUNT_NAME: ${{ secrets.SEPAY_ACCOUNT_NAME }}
      SEPAY_ACCOUNT_NO: ${{ secrets.SEPAY_ACCOUNT_NO }}
      SEPAY_BANK_CODE: ${{ secrets.SEPAY_BANK_CODE }}
      SEPAY_QR_TEMPLATE: ${{ secrets.SEPAY_QR_TEMPLATE }}
      SEPAY_WEBHOOK_API_KEY: ${{ secrets.SEPAY_WEBHOOK_API_KEY }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
